"""add_ghost_scoring

Revision ID: 44b9ca7b1743
Revises: 43c55055b274
Create Date: 2026-03-16 11:12:23.690788+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44b9ca7b1743'
down_revision: Union[str, None] = '43c55055b274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency_reputations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agency_name', sa.String(length=256), nullable=False),
    sa.Column('total_jobs_posted', sa.Integer(), nullable=False, server_default=sa.text('0')),
    sa.Column('total_applications', sa.Integer(), nullable=False, server_default=sa.text('0')),
    sa.Column('total_responses', sa.Integer(), nullable=False, server_default=sa.text('0')),
    sa.Column('response_rate', sa.Float(), nullable=False, server_default=sa.text('0.0')),
    sa.Column('avg_ghost_score', sa.Float(), nullable=False, server_default=sa.text('0.0')),
    sa.Column('reputation', sa.String(length=16), nullable=False, server_default=sa.text("'unknown'")),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_name')
    )
    with op.batch_alter_table('job_postings', schema=None, recreate='always') as batch_op:
        batch_op.add_column(sa.Column('ghost_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ghost_verdict', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('ghost_signals', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ghost_analysed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('first_seen_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('times_seen', sa.Integer(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_job_postings_ghost_score', ['ghost_score'], unique=False)
        batch_op.create_index('idx_job_postings_ghost_verdict', ['ghost_verdict'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_index('idx_job_postings_ghost_verdict')
        batch_op.drop_index('idx_job_postings_ghost_score')
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('times_seen')
        batch_op.drop_column('first_seen_at')
        batch_op.drop_column('ghost_analysed_at')
        batch_op.drop_column('ghost_signals')
        batch_op.drop_column('ghost_verdict')
        batch_op.drop_column('ghost_score')

    op.drop_table('agency_reputations')
    # ### end Alembic commands ###
