"""v2_job_fields_and_auto_apply

Revision ID: c30577e861e2
Revises: a70e739c5a23
Create Date: 2026-03-14 20:44:43.429285+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c30577e861e2'
down_revision: Union[str, None] = 'a70e739c5a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('job_url', sa.String(length=2048), nullable=False),
    sa.Column('apply_url', sa.String(length=2048), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False, server_default=sa.text("'pending'")),
    sa.Column('form_data', sa.Text(), nullable=True),
    sa.Column('custom_questions', sa.Text(), nullable=True),
    sa.Column('cv_path', sa.String(length=512), nullable=True),
    sa.Column('cl_path', sa.String(length=512), nullable=True),
    sa.Column('screenshot_before', sa.String(length=512), nullable=True),
    sa.Column('screenshot_after', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruiter_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('company_name', sa.String(length=256), nullable=True),
    sa.Column('recruiter_name', sa.String(length=256), nullable=True),
    sa.Column('recruiter_title', sa.String(length=256), nullable=True),
    sa.Column('email_guess', sa.String(length=256), nullable=True),
    sa.Column('email_confidence', sa.Float(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('outreach_message', sa.Text(), nullable=True),
    sa.Column('outreach_status', sa.String(length=32), nullable=False, server_default=sa.text("'not_sent'")),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None, recreate='always') as batch_op:
        batch_op.add_column(sa.Column('cv_variant', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('cl_variant', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('response_received', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('response_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('job_postings', schema=None, recreate='always') as batch_op:
        batch_op.add_column(sa.Column('employment_type', sa.String(length=32), nullable=False, server_default=sa.text("'unknown'")))
        batch_op.add_column(sa.Column('working_pattern', sa.String(length=32), nullable=False, server_default=sa.text("'unknown'")))
        batch_op.add_column(sa.Column('rate_type', sa.String(length=16), nullable=False, server_default=sa.text("'unknown'")))
        batch_op.add_column(sa.Column('seniority', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('match_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('match_reasons', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('red_flags', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_column('red_flags')
        batch_op.drop_column('match_reasons')
        batch_op.drop_column('match_score')
        batch_op.drop_column('seniority')
        batch_op.drop_column('rate_type')
        batch_op.drop_column('working_pattern')
        batch_op.drop_column('employment_type')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('response_date')
        batch_op.drop_column('response_received')
        batch_op.drop_column('cl_variant')
        batch_op.drop_column('cv_variant')

    op.drop_table('recruiter_contacts')
    op.drop_table('application_attempts')
    # ### end Alembic commands ###
