"""add runtime foundation

Revision ID: r5s6t7u8v9w0
Revises: q4r5s6t7u8v9
Create Date: 2026-08-25 11:20:28.100368+00:00

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "r5s6t7u8v9w0"
down_revision: Union[str, None] = "q4r5s6t7u8v9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runtime_model_evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=128), nullable=False),
        sa.Column("task_version", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("evidence_type", sa.String(length=64), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtime_workflow_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_definition_id", sa.String(length=128), nullable=False),
        sa.Column("workflow_definition_version", sa.Integer(), nullable=False),
        sa.Column("domain_type", sa.String(length=64), nullable=False),
        sa.Column("domain_id", sa.String(length=128), nullable=True),
        sa.Column(
            "status", sa.String(length=24), server_default="pending", nullable=False
        ),
        sa.Column("runtime_mode", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("input_ref_json", sa.JSON(), nullable=True),
        sa.Column("result_ref_json", sa.JSON(), nullable=True),
        sa.Column("failure_code", sa.String(length=128), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtime_workflow_steps",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_run_id", sa.String(length=36), nullable=False),
        sa.Column("step_key", sa.String(length=128), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.String(length=128), nullable=False),
        sa.Column("task_version", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=24), server_default="pending", nullable=False
        ),
        sa.Column("waiting_reason", sa.String(length=24), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("failure_code", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["runtime_workflow_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_run_id", "step_key", name="uq_runtime_step_key"),
    )
    op.create_table(
        "runtime_task_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_step_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("prior_attempt_id", sa.String(length=36), nullable=True),
        sa.Column(
            "status", sa.String(length=24), server_default="pending", nullable=False
        ),
        sa.Column("waiting_reason", sa.String(length=24), nullable=True),
        sa.Column("not_before", sa.DateTime(), nullable=True),
        sa.Column("retry_reason", sa.String(length=128), nullable=True),
        sa.Column("retry_policy_id", sa.String(length=128), nullable=True),
        sa.Column("retry_policy_version", sa.Integer(), nullable=True),
        sa.Column(
            "claim_fencing_token", sa.BigInteger(), server_default="0", nullable=False
        ),
        sa.Column("current_claim_id", sa.String(length=36), nullable=True),
        sa.Column("context_package_id", sa.String(length=36), nullable=True),
        sa.Column("result_ref_json", sa.JSON(), nullable=True),
        sa.Column("failure_code", sa.String(length=128), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prior_attempt_id"],
            ["runtime_task_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_step_id"],
            ["runtime_workflow_steps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workflow_step_id", "attempt_number", name="uq_runtime_attempt_number"
        ),
    )
    op.create_table(
        "runtime_approvals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_run_id", sa.String(length=36), nullable=False),
        sa.Column("workflow_step_id", sa.String(length=36), nullable=True),
        sa.Column("task_attempt_id", sa.String(length=36), nullable=True),
        sa.Column("capability_id", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=128), nullable=False),
        sa.Column("payload_hash_algorithm", sa.String(length=32), nullable=False),
        sa.Column(
            "status", sa.String(length=24), server_default="pending", nullable=False
        ),
        sa.Column("requested_at", sa.DateTime(), nullable=False),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.Column("decided_by", sa.String(length=128), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("decision_reason", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_attempt_id"],
            ["runtime_task_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["runtime_workflow_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_step_id"],
            ["runtime_workflow_steps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtime_context_packages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_attempt_id", sa.String(length=36), nullable=False),
        sa.Column("package_version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("token_estimate", sa.Integer(), nullable=False),
        sa.Column("sensitivity_max", sa.String(length=24), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=False),
        sa.Column("items_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_attempt_id"],
            ["runtime_task_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtime_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("event_version", sa.Integer(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=128), nullable=False),
        sa.Column("workflow_run_id", sa.String(length=36), nullable=True),
        sa.Column("workflow_step_id", sa.String(length=36), nullable=True),
        sa.Column("task_attempt_id", sa.String(length=36), nullable=True),
        sa.Column("actor_type", sa.String(length=24), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("causation_event_id", sa.String(length=36), nullable=True),
        sa.Column("sensitivity", sa.String(length=24), nullable=False),
        sa.ForeignKeyConstraint(
            ["causation_event_id"],
            ["runtime_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_attempt_id"],
            ["runtime_task_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["runtime_workflow_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_step_id"],
            ["runtime_workflow_steps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtime_execution_claims",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_attempt_id", sa.String(length=36), nullable=False),
        sa.Column("fencing_token", sa.BigInteger(), nullable=False),
        sa.Column("claimed_by", sa.String(length=128), nullable=False),
        sa.Column("claimed_at", sa.DateTime(), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(), nullable=False),
        sa.Column("released_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status", sa.String(length=24), server_default="active", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["task_attempt_id"],
            ["runtime_task_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "task_attempt_id", "fencing_token", name="uq_runtime_claim_fence"
        ),
    )
    op.create_table(
        "runtime_execution_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_attempt_id", sa.String(length=36), nullable=False),
        sa.Column("parent_execution_id", sa.String(length=36), nullable=True),
        sa.Column("execution_role", sa.String(length=24), nullable=False),
        sa.Column("capability_id", sa.String(length=128), nullable=False),
        sa.Column("capability_version", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=True),
        sa.Column("model_version", sa.String(length=128), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("strategy_stage", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("result_class", sa.String(length=32), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("span_id", sa.String(length=32), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_execution_id"],
            ["runtime_execution_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_attempt_id"],
            ["runtime_task_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtime_policy_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_attempt_id", sa.String(length=36), nullable=False),
        sa.Column("policy_id", sa.String(length=128), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_attempt_id"],
            ["runtime_task_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtime_routing_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_attempt_id", sa.String(length=36), nullable=False),
        sa.Column("router_id", sa.String(length=128), nullable=False),
        sa.Column("router_version", sa.Integer(), nullable=False),
        sa.Column("capability_id", sa.String(length=128), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("reason_codes_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_attempt_id"],
            ["runtime_task_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtime_evaluation_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_attempt_id", sa.String(length=36), nullable=False),
        sa.Column("execution_id", sa.String(length=36), nullable=True),
        sa.Column("evaluator_id", sa.String(length=128), nullable=False),
        sa.Column("evaluator_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["runtime_execution_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_attempt_id"],
            ["runtime_task_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtime_outbox",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("destination", sa.String(length=128), nullable=False),
        sa.Column(
            "status", sa.String(length=24), server_default="pending", nullable=False
        ),
        sa.Column("not_before", sa.DateTime(), nullable=False),
        sa.Column("claim_id", sa.String(length=36), nullable=True),
        sa.Column("fencing_token", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["runtime_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtime_shadow_comparisons",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slice_name", sa.String(length=64), nullable=False),
        sa.Column("domain_type", sa.String(length=64), nullable=False),
        sa.Column("domain_id_hash", sa.String(length=128), nullable=False),
        sa.Column("legacy_execution_ref", sa.String(length=128), nullable=True),
        sa.Column("runtime_execution_id", sa.String(length=36), nullable=True),
        sa.Column("legacy_result_hash", sa.String(length=128), nullable=False),
        sa.Column("runtime_result_hash", sa.String(length=128), nullable=False),
        sa.Column("comparison_status", sa.String(length=32), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["runtime_execution_id"],
            ["runtime_execution_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtime_validation_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_attempt_id", sa.String(length=36), nullable=False),
        sa.Column("execution_id", sa.String(length=36), nullable=True),
        sa.Column("validator_id", sa.String(length=128), nullable=False),
        sa.Column("validator_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("reason_codes_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["runtime_execution_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_attempt_id"],
            ["runtime_task_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtime_evidence_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("evaluation_run_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_type", sa.String(length=64), nullable=False),
        sa.Column("source_ref", sa.String(length=256), nullable=False),
        sa.Column("observation_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_run_id"],
            ["runtime_evaluation_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtime_outbox_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("outbox_entry_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("result", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["outbox_entry_id"],
            ["runtime_outbox.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "outbox_entry_id", "attempt_number", name="uq_runtime_outbox_attempt"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("runtime_outbox_attempts")
    op.drop_table("runtime_evidence_observations")
    op.drop_table("runtime_validation_results")
    op.drop_table("runtime_shadow_comparisons")
    op.drop_table("runtime_outbox")
    op.drop_table("runtime_evaluation_runs")
    op.drop_table("runtime_routing_decisions")
    op.drop_table("runtime_policy_decisions")
    op.drop_table("runtime_execution_records")
    op.drop_table("runtime_execution_claims")
    op.drop_table("runtime_events")
    op.drop_table("runtime_context_packages")
    op.drop_table("runtime_approvals")
    op.drop_table("runtime_task_attempts")
    op.drop_table("runtime_workflow_steps")
    op.drop_table("runtime_workflow_runs")
    op.drop_table("runtime_model_evidence")
    # ### end Alembic commands ###
