"""add_fk_application_attempts_application_id

Revision ID: 2d22dcc71570
Revises: 44b9ca7b1743
Create Date: 2026-03-16 14:08:37.533842+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d22dcc71570'
down_revision: Union[str, None] = '44b9ca7b1743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_attempts', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_application_attempts_application_id', 'applications', ['application_id'], ['id'])

    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.alter_column('times_seen',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.alter_column('times_seen',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('application_attempts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_application_attempts_application_id', type_='foreignkey')

    # ### end Alembic commands ###
