"""add_follow_up_emails

Revision ID: 43c55055b274
Revises: c30577e861e2
Create Date: 2026-03-16 11:04:07.823474+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43c55055b274'
down_revision: Union[str, None] = 'c30577e861e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_up_emails',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('follow_up_id', sa.String(length=36), nullable=True),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('email_type', sa.String(length=32), nullable=False),
    sa.Column('recipient_email', sa.String(length=256), nullable=True),
    sa.Column('recipient_name', sa.String(length=256), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('body_plain', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sent_via', sa.String(length=16), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('generation_params', sa.Text(), nullable=True),
    sa.Column('user_edits', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['follow_up_id'], ['follow_ups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('follow_up_emails', schema=None) as batch_op:
        batch_op.create_index('idx_follow_up_emails_application_id', ['application_id'], unique=False)
        batch_op.create_index('idx_follow_up_emails_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_follow_up_emails_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up_emails', schema=None) as batch_op:
        batch_op.drop_index('idx_follow_up_emails_status')
        batch_op.drop_index('idx_follow_up_emails_created_at')
        batch_op.drop_index('idx_follow_up_emails_application_id')

    op.drop_table('follow_up_emails')
    # ### end Alembic commands ###
